In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from scikeras.wrappers import KerasClassifier
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import pickle

In [29]:
data = pd.read_csv('churn_modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [30]:
data = data.drop(['RowNumber','CustomerId','Surname'], axis = 1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [31]:
hp_label_encoder_gender = LabelEncoder()
data['Gender'] = hp_label_encoder_gender.fit_transform(data['Gender'])

In [32]:
hp_one_hot_Encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = hp_one_hot_Encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=hp_one_hot_Encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [33]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [34]:
X = data.drop('Exited', axis = 1)
Y = data['Exited']

In [35]:
# split the data into training and testing set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)   

## Scale these features
hp_scaler = StandardScaler()
X_train = hp_scaler.fit_transform(X_train)
X_test = hp_scaler.transform(X_test)

In [36]:
with open('hp_scaler.pkl', 'wb') as f:
    pickle.dump(hp_scaler, f)

## Save the encoders and scaler for future use
with open('hp_label_enc_gender.pkl', 'wb') as f:
    pickle.dump(hp_label_encoder_gender, f)

with open('hp_one_hot_encoder_geography.pkl', 'wb') as f:
    pickle.dump(hp_one_hot_Encoder_geo, f)

In [46]:
## define a function to create the model and try different hyperparameters(keras classifier)

def create_model(neurons=32, layers=1):
    model = Sequential()
    model.add(Dense(neurons, activation='relu', input_shape=(X_train.shape[1],)))
    
    for _ in range(layers-1):
        model.add(Dense(neurons, activation='relu'))
    
    model.add(Dense(1, activation='sigmoid'))
    
    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    
    return model

In [48]:
## Create a keras classifier
model = KerasClassifier(layers=1, neurons=32, build_fn=create_model, verbose=1)

In [49]:
#define grid search parameters
param_grid = {
    'neurons': [16, 32, 64, 128],
    'layers': [1, 2, 3],
    # 'batch_size': [10],
    'epochs': [50, 100]
}

In [50]:
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=-1, cv=3, verbose=1)
grid_result = grid.fit(X_train, Y_train)

print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")

Fitting 3 folds for each of 24 candidates, totalling 72 fits
WARNING:tensorflow:From c:\LearningWS\MachineLearning\mlenv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

WARNING:tensorflow:From c:\LearningWS\MachineLearning\mlenv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

c:\LearningWS\MachineLearning\mlenv\Lib\site-packages\scikeras\wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.
  X, y = self._initialize(X, y)

Epoch 1/50
WARNING:tensorflow:From c:\LearningWS\MachineLearning\mlenv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\LearningWS\MachineLearning\mlenv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 1s 919us/step - loss: 0.4692 - accuracy: 0.7835
Epoch 2/50
250/250 [==============================] - 0s 755us/step - loss: 0.3946 - accuracy: 0.8353
Epoch 3/50
250/250 [==============================] - 0s 801us/step - loss: 0.3680 - accuracy: 0.8481
Epoch 4/50
250/250 [==============================] - 0s 809us/step - loss: 0.3548 - accuracy: 0.8549
Epoch 5/50
250/250 [==============================] - 0s 772us/step - loss: 0.3489 - accuracy: 0.8558
Epoch 6/50
250/250 [==============================] - 0s 805us/step - loss: 0.3460 - accuracy: 0.8575
Epoch 7/50
250/250 [==============================] - 0s 824us/step - loss: 0.3439 - accuracy: 0.8599
Epoch 8/50
250/250 [==============================] - 0s 848us/step - loss: 0.3408 - accuracy: 0.8604
Epoch 9/50
250/250 [==============================] - 0s 821us/step - loss: 0.3391 - accuracy: 0.8605
Epoch 10/50
250/250 [==============================] - 0s 878us/step - loss: 0.3390 - accuracy: 0.8609
Epoch 11/50
250/250 [==============================] - 0s 860us/step - loss: 0.3371 - accuracy: 0.8634
Epoch 12/50
250/250 [==============================] - 0s 855us/step - loss: 0.3370 - accuracy: 0.8584
Epoch 13/50
250/250 [==============================] - 0s 948us/step - loss: 0.3341 - accuracy: 0.8608
Epoch 14/50
250/250 [==============================] - 0s 877us/step - loss: 0.3345 - accuracy: 0.8616
Epoch 15/50
250/250 [==============================] - 0s 882us/step - loss: 0.3341 - accuracy: 0.8608
Epoch 16/50
250/250 [==============================] - 0s 939us/step - loss: 0.3339 - accuracy: 0.8608
Epoch 17/50
250/250 [==============================] - 0s 845us/step - loss: 0.3324 - accuracy: 0.8624
Epoch 18/50
250/250 [==============================] - 0s 835us/step - loss: 0.3315 - accuracy: 0.8622
Epoch 19/50
250/250 [==============================] - 0s 725us/step - loss: 0.3301 - accuracy: 0.8626
Epoch 20/50
250/250 [==============================] - 0s 818us/step - loss: 0.3297 - accuracy: 0.8635
Epoch 21/50
250/250 [==============================] - 0s 878us/step - loss: 0.3288 - accuracy: 0.8640
Epoch 22/50
250/250 [==============================] - 0s 775us/step - loss: 0.3278 - accuracy: 0.8658
Epoch 23/50
250/250 [==============================] - 0s 747us/step - loss: 0.3281 - accuracy: 0.8649
Epoch 24/50
250/250 [==============================] - 0s 742us/step - loss: 0.3271 - accuracy: 0.8659
Epoch 25/50
250/250 [==============================] - 0s 750us/step - loss: 0.3259 - accuracy: 0.8655
Epoch 26/50
250/250 [==============================] - 0s 731us/step - loss: 0.3249 - accuracy: 0.8659
Epoch 27/50
250/250 [==============================] - 0s 737us/step - loss: 0.3231 - accuracy: 0.8677
Epoch 28/50
250/250 [==============================] - 0s 785us/step - loss: 0.3234 - accuracy: 0.8665
Epoch 29/50
250/250 [==============================] - 0s 745us/step - loss: 0.3224 - accuracy: 0.8652
Epoch 30/50
250/250 [==============================] - 0s 744us/step - loss: 0.3218 - accuracy: 0.8658
Epoch 31/50
250/250 [==============================] - 0s 733us/step - loss: 0.3198 - accuracy: 0.8668
Epoch 32/50
250/250 [==============================] - 0s 729us/step - loss: 0.3196 - accuracy: 0.8664
Epoch 33/50
250/250 [==============================] - 0s 862us/step - loss: 0.3186 - accuracy: 0.8656
Epoch 34/50
250/250 [==============================] - 0s 792us/step - loss: 0.3183 - accuracy: 0.8696
Epoch 35/50
250/250 [==============================] - 0s 875us/step - loss: 0.3166 - accuracy: 0.8685
Epoch 36/50
250/250 [==============================] - 0s 875us/step - loss: 0.3167 - accuracy: 0.8705
Epoch 37/50
250/250 [==============================] - 0s 837us/step - loss: 0.3164 - accuracy: 0.8695
Epoch 38/50
250/250 [==============================] - 0s 857us/step - loss: 0.3153 - accuracy: 0.8689
Epoch 39/50
250/250 [==============================] - 0s 740us/step - loss: 0.3150 - accuracy: 0.8684
Epoch 40/50
250/250 [==============================] - 0s 937us/step - loss: 0.3146 - accuracy: 0.8706
Epoch 41/50
250/250 [==============================] - 0s 882us/step - loss: 0.3132 - accuracy: 0.8690
Epoch 42/50
250/250 [==============================] - 0s 955us/step - loss: 0.3137 - accuracy: 0.8702
Epoch 43/50
250/250 [==============================] - 0s 811us/step - loss: 0.3134 - accuracy: 0.8692
Epoch 44/50
250/250 [==============================] - 0s 762us/step - loss: 0.3119 - accuracy: 0.8720
Epoch 45/50
250/250 [==============================] - 0s 1ms/step - loss: 0.3124 - accuracy: 0.8687
Epoch 46/50
250/250 [==============================] - 0s 885us/step - loss: 0.3120 - accuracy: 0.8696
Epoch 47/50
250/250 [==============================] - 0s 936us/step - loss: 0.3114 - accuracy: 0.8730
Epoch 48/50
250/250 [==============================] - 0s 850us/step - loss: 0.3105 - accuracy: 0.8712
Epoch 49/50
250/250 [==============================] - 0s 788us/step - loss: 0.3108 - accuracy: 0.8708
Epoch 50/50
250/250 [==============================] - 0s 862us/step - loss: 0.3096 - accuracy: 0.8700
Best: 0.8573742141947185 using {'epochs': 50, 'layers': 1, 'neurons': 128}