In [21]:
import pandas as pd
import streamlit as st
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import numpy as np
import tensorflow as tf
#from tensorflow.keras.models import Sequential, load_model
#from tensorflow.keras.layers import Dense
#from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import pickle
import os

In [22]:
data = pd.read_csv('churn_modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [23]:
data = data.drop(['RowNumber','CustomerId','Surname'], axis = 1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [24]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [25]:
one_hot_Encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = one_hot_Encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=one_hot_Encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [26]:
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [27]:
X = data.drop('EstimatedSalary', axis = 1)
Y = data['EstimatedSalary']

# split the data into training and testing set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)   

## Scale these features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [28]:
with open('sl_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

## Save the encoders and scaler for future use
with open('sl_label_enc_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)

with open('sl_one_hot_encoder_geography.pkl', 'wb') as f:
    pickle.dump(one_hot_Encoder_geo, f)

In [29]:
## ANN with regrattion problem statement
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [30]:
model = Sequential([
    Dense(64, activation='relu',input_shape=(X_train.shape[1],)), # Hidden Layer 1 connected to input layer
    Dense(32, activation='relu'), # Hidden Layer 2
    Dense(1,) # Output layer with linear activation function
])

#complie the model 
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [31]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "reglogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [32]:
EarlyStopping_Callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [33]:
history = model.fit(
    X_train, 
    Y_train, 
    validation_data=(X_test, Y_test), 
    epochs=100, 
    callbacks=[EarlyStopping_Callback, 
               tensorflow_callback]
    )

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 100388.4531 - mae: 100388.4531 - val_loss: 98555.6328 - val_mae: 98555.6328
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 99757.7500 - mae: 99757.7500 - val_loss: 97264.9453 - val_mae: 97264.9453
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 97499.4453 - mae: 97499.4453 - val_loss: 93921.0391 - val_mae: 93921.0391
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 92980.0391 - mae: 92980.0391 - val_loss: 88215.5156 - val_mae: 88215.5156
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 86251.9453 - mae: 86251.9453 - val_loss: 80601.5938 - val_mae: 80601.5938
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 77980.0625 - mae: 77980.0625 - val_loss: 72246.0938 - val_mae: 72246.0938
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 69425.2188 - mae: 69425.2188 - val_loss: 64405.3281 - val_mae: 64405.3281
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 61925.4375 - mae: 61925.4375 - val_loss: 58251.0703 - val_mae: 58251.0703
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 56547.4258 - mae: 56547.4258 - val_loss: 54274.2773 - val_mae: 54274.2773
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 53192.3711 - mae: 53192.3711 - val_loss: 52121.6914 - val_mae: 52121.6914
Epoch 11/100
250/250 [==============================] - 0s 1ms/step - loss: 51473.7383 - mae: 51473.7383 - val_loss: 51243.7773 - val_mae: 51243.7773
Epoch 12/100
250/250 [==============================] - 0s 1ms/step - loss: 50706.6367 - mae: 50706.6367 - val_loss: 50941.7188 - val_mae: 50941.7188
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 50414.3906 - mae: 50414.3906 - val_loss: 50835.0195 - val_mae: 50835.0195
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 50286.4883 - mae: 50286.4883 - val_loss: 50774.8398 - val_mae: 50774.8398
Epoch 15/100
250/250 [==============================] - 0s 1ms/step - loss: 50210.0625 - mae: 50210.0625 - val_loss: 50733.2578 - val_mae: 50733.2578
Epoch 16/100
250/250 [==============================] - 0s 1ms/step - loss: 50150.6250 - mae: 50150.6250 - val_loss: 50685.9062 - val_mae: 50685.9062
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 50101.1484 - mae: 50101.1484 - val_loss: 50661.0039 - val_mae: 50661.0039
Epoch 18/100
250/250 [==============================] - 0s 1ms/step - loss: 50056.7422 - mae: 50056.7422 - val_loss: 50634.2266 - val_mae: 50634.2266
Epoch 19/100
250/250 [==============================] - 0s 1ms/step - loss: 50014.7383 - mae: 50014.7383 - val_loss: 50613.2188 - val_mae: 50613.2188
Epoch 20/100
250/250 [==============================] - 0s 1ms/step - loss: 49982.3008 - mae: 49982.3008 - val_loss: 50584.6016 - val_mae: 50584.6016
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 49944.0000 - mae: 49944.0000 - val_loss: 50566.7344 - val_mae: 50566.7344
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 49912.6602 - mae: 49912.6602 - val_loss: 50549.1406 - val_mae: 50549.1406
Epoch 23/100
250/250 [==============================] - 0s 1ms/step - loss: 49885.1602 - mae: 49885.1602 - val_loss: 50523.9023 - val_mae: 50523.9023
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 49858.4922 - mae: 49858.4922 - val_loss: 50504.7930 - val_mae: 50504.7930
Epoch 25/100
250/250 [==============================] - 0s 1ms/step - loss: 49833.1602 - mae: 49833.1602 - val_loss: 50488.3008 - val_mae: 50488.3008
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49812.2773 - mae: 49812.2773 - val_loss: 50475.2266 - val_mae: 50475.2266
Epoch 27/100
250/250 [==============================] - 0s 1ms/step - loss: 49793.3594 - mae: 49793.3594 - val_loss: 50462.4844 - val_mae: 50462.4844
Epoch 28/100
250/250 [==============================] - 0s 1ms/step - loss: 49776.9492 - mae: 49776.9492 - val_loss: 50450.4492 - val_mae: 50450.4492
Epoch 29/100
250/250 [==============================] - 0s 1ms/step - loss: 49757.6875 - mae: 49757.6875 - val_loss: 50430.3086 - val_mae: 50430.3086
Epoch 30/100
250/250 [==============================] - 0s 1ms/step - loss: 49737.2656 - mae: 49737.2656 - val_loss: 50422.9258 - val_mae: 50422.9258
Epoch 31/100
250/250 [==============================] - 0s 1ms/step - loss: 49723.2734 - mae: 49723.2734 - val_loss: 50419.5781 - val_mae: 50419.5781
Epoch 32/100
250/250 [==============================] - 0s 1ms/step - loss: 49707.9414 - mae: 49707.9414 - val_loss: 50409.9219 - val_mae: 50409.9219
Epoch 33/100
250/250 [==============================] - 0s 1ms/step - loss: 49692.0234 - mae: 49692.0234 - val_loss: 50407.6758 - val_mae: 50407.6758
Epoch 34/100
250/250 [==============================] - 0s 1ms/step - loss: 49679.5508 - mae: 49679.5508 - val_loss: 50397.9883 - val_mae: 50397.9883
Epoch 35/100
250/250 [==============================] - 0s 1ms/step - loss: 49668.2227 - mae: 49668.2227 - val_loss: 50401.5742 - val_mae: 50401.5742
Epoch 36/100
250/250 [==============================] - 0s 1ms/step - loss: 49653.4805 - mae: 49653.4805 - val_loss: 50388.1680 - val_mae: 50388.1680
Epoch 37/100
250/250 [==============================] - 0s 1ms/step - loss: 49644.1641 - mae: 49644.1641 - val_loss: 50380.6875 - val_mae: 50380.6875
Epoch 38/100
250/250 [==============================] - 0s 1ms/step - loss: 49632.6797 - mae: 49632.6797 - val_loss: 50370.9102 - val_mae: 50370.9102
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49620.8203 - mae: 49620.8203 - val_loss: 50375.8438 - val_mae: 50375.8438
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49609.8359 - mae: 49609.8359 - val_loss: 50376.1836 - val_mae: 50376.1836
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49599.4727 - mae: 49599.4727 - val_loss: 50371.2773 - val_mae: 50371.2773
Epoch 42/100
250/250 [==============================] - 0s 1ms/step - loss: 49591.3633 - mae: 49591.3633 - val_loss: 50363.1133 - val_mae: 50363.1133
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49580.8984 - mae: 49580.8984 - val_loss: 50364.8711 - val_mae: 50364.8711
Epoch 44/100
250/250 [==============================] - 0s 1ms/step - loss: 49571.8633 - mae: 49571.8633 - val_loss: 50362.1172 - val_mae: 50362.1172
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49566.3906 - mae: 49566.3906 - val_loss: 50358.7617 - val_mae: 50358.7617
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 49552.9922 - mae: 49552.9922 - val_loss: 50361.8516 - val_mae: 50361.8516
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49547.3398 - mae: 49547.3398 - val_loss: 50365.6836 - val_mae: 50365.6836
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49539.8906 - mae: 49539.8906 - val_loss: 50362.7695 - val_mae: 50362.7695
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49528.0430 - mae: 49528.0430 - val_loss: 50362.2617 - val_mae: 50362.2617
Epoch 50/100
250/250 [==============================] - 0s 1ms/step - loss: 49520.9609 - mae: 49520.9609 - val_loss: 50351.4297 - val_mae: 50351.4297
Epoch 51/100
250/250 [==============================] - 0s 1ms/step - loss: 49513.9023 - mae: 49513.9023 - val_loss: 50351.2812 - val_mae: 50351.2812
Epoch 52/100
250/250 [==============================] - 0s 1ms/step - loss: 49505.6836 - mae: 49505.6836 - val_loss: 50352.3398 - val_mae: 50352.3398
Epoch 53/100
250/250 [==============================] - 0s 1ms/step - loss: 49500.2734 - mae: 49500.2734 - val_loss: 50350.4062 - val_mae: 50350.4062
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 49493.3047 - mae: 49493.3047 - val_loss: 50344.5273 - val_mae: 50344.5273
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 49488.0273 - mae: 49488.0273 - val_loss: 50349.8594 - val_mae: 50349.8594
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 49479.0000 - mae: 49479.0000 - val_loss: 50353.3750 - val_mae: 50353.3750
Epoch 57/100
250/250 [==============================] - 0s 1ms/step - loss: 49477.8242 - mae: 49477.8242 - val_loss: 50353.7148 - val_mae: 50353.7148
Epoch 58/100
250/250 [==============================] - 0s 1ms/step - loss: 49470.2617 - mae: 49470.2617 - val_loss: 50347.6367 - val_mae: 50347.6367
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 49462.8320 - mae: 49462.8320 - val_loss: 50349.1328 - val_mae: 50349.1328
Epoch 60/100
250/250 [==============================] - 0s 1ms/step - loss: 49455.6758 - mae: 49455.6758 - val_loss: 50346.2617 - val_mae: 50346.2617
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 49451.2617 - mae: 49451.2617 - val_loss: 50350.3945 - val_mae: 50350.3945
Epoch 62/100
250/250 [==============================] - 0s 2ms/step - loss: 49450.0234 - mae: 49450.0234 - val_loss: 50354.8203 - val_mae: 50354.8203
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 49440.7031 - mae: 49440.7031 - val_loss: 50352.2812 - val_mae: 50352.2812
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: 49436.1914 - mae: 49436.1914 - val_loss: 50348.8828 - val_mae: 50348.8828

In [34]:
## Load Tenserboard extendsion

%reload_ext tensorboard
model.save('Regrassion.h5')

c:\LearningWS\MachineLearning\mlenv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [35]:
## Load Tenserboard extendsion
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [36]:
%tensorboard --logdir reglogs/fit/

ERROR: Could not find `tensorboard`. Please ensure that your PATH
contains an executable `tensorboard` program, or explicitly specify
the path to a TensorBoard binary by setting the `TENSORBOARD_BINARY`
environment variable.

In [37]:
## Evaluate the model on the test set
test_loss, test_mae = model.evaluate(X_test, Y_test)
print(f"Test Loss: {test_loss}, Test MAE: {test_mae}")

63/63 [==============================] - 0s 908us/step - loss: 50344.5273 - mae: 50344.5273
Test Loss: 50344.52734375, Test MAE: 50344.52734375